version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_trasaction
    healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost","--silent"]
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    build:
     context: .
     dockerfile: Dockerfile
    depends_on:
      mysqldb:
       condition: service_healthy
    image: trsacation-service:1.0
    ports:
      - 9090:9090
    environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/db_trasaction"
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: